Repository mafia-together/backend, pull requests merged in 2024-05, with the labels that each got.

#16 fix: 방 유저 예외처리 추가
  src/main/java/mafia/mafiatogether/domain/Room.java
Labels: Backend

#20 Github action CI script
  .github/workflows/backend-CI.yml
Labels: Backend

#22 fix: script 빌드 브랜치 수정
  .github/workflows/backend-CI.yml
Labels: Backend

#30 cors 에러 수정
  src/main/java/mafia/mafiatogether/config/WebMvcConfig.java
Labels: Backend

#31 cors 에러 origin 수정
  src/main/java/mafia/mafiatogether/config/WebMvcConfig.java
Labels: Backend

#25 feat: 에러 핸들링 구현
  src/main/java/mafia/mafiatogether/config/exception/AuthException.java
  src/main/java/mafia/mafiatogether/config/exception/CitizenException.java
  src/main/java/mafia/mafiatogether/config/exception/ErrorResponse.java
  src/main/java/mafia/mafiatogether/config/exception/ExceptionCode.java
  src/main/java/mafia/mafiatogether/config/exception/GlobalException.java
  src/main/java/mafia/mafiatogether/config/exception/GlobalExceptionHandler.java
  src/main/java/mafia/mafiatogether/config/exception/RoomException.java
  src/main/java/mafia/mafiatogether/controller/PlayerArgumentResolver.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/RoomManager.java
  src/main/java/mafia/mafiatogether/domain/job/Citizen.java
  src/test/java/mafia/mafiatogether/controller/ChatControllerTest.java
Labels: Backend

#33 fix: localhost:5173 cors origin 추가
  src/main/java/mafia/mafiatogether/config/WebMvcConfig.java
Labels: Backend

#32 방 시간 경과 기능 구현 및 Roominfo 조회 기능 구현
  src/main/java/mafia/mafiatogether/controller/RoomController.java
  src/main/java/mafia/mafiatogether/domain/Player.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/RoomManager.java
  src/main/java/mafia/mafiatogether/domain/Status.java
  src/main/java/mafia/mafiatogether/domain/Vote.java
  src/main/java/mafia/mafiatogether/domain/job/Citizen.java
  src/main/java/mafia/mafiatogether/domain/job/Doctor.java
  src/main/java/mafia/mafiatogether/domain/job/Job.java
  src/main/java/mafia/mafiatogether/domain/job/JobTarget.java
  src/main/java/mafia/mafiatogether/domain/job/Mafia.java
  src/main/java/mafia/mafiatogether/domain/job/Police.java
  src/main/java/mafia/mafiatogether/domain/status/DayStatus.java
  src/main/java/mafia/mafiatogether/domain/status/EndStatus.java
  src/main/java/mafia/mafiatogether/domain/status/NightStatus.java
  src/main/java/mafia/mafiatogether/domain/status/Status.java
  src/main/java/mafia/mafiatogether/domain/status/StatusType.java
  src/main/java/mafia/mafiatogether/domain/status/VoteStatus.java
  src/main/java/mafia/mafiatogether/domain/status/WaitStatus.java
  src/main/java/mafia/mafiatogether/service/RoomService.java
  src/main/java/mafia/mafiatogether/service/dto/PlayerResponse.java
  src/main/java/mafia/mafiatogether/service/dto/RoomInfoResponse.java
  src/main/java/mafia/mafiatogether/service/dto/RoomModifyRequest.java
  src/main/java/mafia/mafiatogether/service/dto/RoomStatusResponse.java
  src/test/java/mafia/mafiatogether/controller/PlayerControllerTest.java
  src/test/java/mafia/mafiatogether/controller/RoomControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomTest.java
  src/test/java/mafia/mafiatogether/domain/job/JobTargetTest.java
  src/test/java/mafia/mafiatogether/domain/status/StatusTest.java
Labels: Backend

#35 fix: dto 필드값 변경 및 반환값 변경
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/service/dto/RoomInfoResponse.java
Labels: Backend

#34 feat: api 수정 사항 반영
  src/main/java/mafia/mafiatogether/controller/PlayerController.java
  src/main/java/mafia/mafiatogether/controller/RoomController.java
  src/main/java/mafia/mafiatogether/domain/Player.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/RoomManager.java
  src/main/java/mafia/mafiatogether/domain/job/Citizen.java
  src/main/java/mafia/mafiatogether/domain/job/Doctor.java
  src/main/java/mafia/mafiatogether/domain/job/Job.java
  src/main/java/mafia/mafiatogether/domain/job/Mafia.java
  src/main/java/mafia/mafiatogether/domain/job/Police.java
  src/main/java/mafia/mafiatogether/service/PlayerService.java
  src/main/java/mafia/mafiatogether/service/RoomService.java
  src/main/java/mafia/mafiatogether/service/dto/ChatResponse.java
  src/main/java/mafia/mafiatogether/service/dto/JobResponse.java
  src/main/java/mafia/mafiatogether/service/dto/MafiaTargetResponse.java
  src/main/java/mafia/mafiatogether/service/dto/PlayerResponse.java
  src/main/java/mafia/mafiatogether/service/dto/RoomValidateResponse.java
  src/test/java/mafia/mafiatogether/controller/PlayerControllerTest.java
  src/test/java/mafia/mafiatogether/controller/RoomControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomManagerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomTest.java
Labels: Backend

#39 hotfix cors error https 추가
  src/main/java/mafia/mafiatogether/config/WebMvcConfig.java
Labels: Backend

#37 기타 예외사항 구현
  src/main/java/mafia/mafiatogether/config/exception/ErrorResponse.java
  src/main/java/mafia/mafiatogether/config/exception/ExceptionCode.java
  src/main/java/mafia/mafiatogether/config/exception/GlobalExceptionHandler.java
  src/main/java/mafia/mafiatogether/controller/ChatController.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/RoomInfo.java
  src/main/java/mafia/mafiatogether/domain/job/JobTarget.java
  src/main/java/mafia/mafiatogether/domain/status/WaitStatus.java
  src/main/java/mafia/mafiatogether/service/PlayerService.java
  src/main/java/mafia/mafiatogether/service/RoomService.java
  src/main/java/mafia/mafiatogether/service/dto/ChatRequest.java
  src/main/java/mafia/mafiatogether/service/dto/RoomCreateRequest.java
  src/test/java/mafia/mafiatogether/controller/ChatControllerTest.java
  src/test/java/mafia/mafiatogether/controller/PlayerControllerTest.java
  src/test/java/mafia/mafiatogether/controller/RoomControllerTest.java
  src/test/java/mafia/mafiatogether/controller/VoteControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomTest.java
  src/test/java/mafia/mafiatogether/domain/status/StatusTest.java
Labels: Backend

#41 feat: RoomInfoResponse myName 필드 추가 및 마피아 반환 로직 구현
  src/main/java/mafia/mafiatogether/domain/Player.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/job/Citizen.java
  src/main/java/mafia/mafiatogether/domain/job/Doctor.java
  src/main/java/mafia/mafiatogether/domain/job/Job.java
  src/main/java/mafia/mafiatogether/domain/job/Mafia.java
  src/main/java/mafia/mafiatogether/domain/job/Police.java
  src/main/java/mafia/mafiatogether/service/PlayerService.java
  src/main/java/mafia/mafiatogether/service/RoomService.java
  src/main/java/mafia/mafiatogether/service/dto/PlayerResponse.java
  src/main/java/mafia/mafiatogether/service/dto/RoomInfoResponse.java
  src/test/java/mafia/mafiatogether/controller/PlayerControllerTest.java
  src/test/java/mafia/mafiatogether/controller/RoomControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomTest.java
Labels: Backend

#46 feat: 결과 조회 기능 구현
  src/main/java/mafia/mafiatogether/config/exception/ExceptionCode.java
  src/main/java/mafia/mafiatogether/controller/RoomController.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/status/EndStatus.java
  src/main/java/mafia/mafiatogether/domain/status/NightStatus.java
  src/main/java/mafia/mafiatogether/domain/status/VoteResultStatus.java
  src/main/java/mafia/mafiatogether/service/RoomService.java
  src/main/java/mafia/mafiatogether/service/dto/RoomResultPlayerDto.java
  src/main/java/mafia/mafiatogether/service/dto/RoomResultResponse.java
  src/test/java/mafia/mafiatogether/domain/status/EndStatusTest.java
Labels: Backend

#49 fix: 투표결과 조회 기능 수정
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/Vote.java
  src/main/java/mafia/mafiatogether/domain/status/VoteResultStatus.java
  src/test/java/mafia/mafiatogether/controller/VoteControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomTest.java
  src/test/java/mafia/mafiatogether/domain/status/StatusTest.java
Labels: Backend

#53 게임 종료시 방 초기화 구현
  src/main/java/mafia/mafiatogether/domain/Player.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/status/EndStatus.java
  src/test/java/mafia/mafiatogether/domain/status/StatusTest.java
Labels: Backend

#55 모든 플레이어 투표 완료시 상태 변경
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/Vote.java
  src/main/java/mafia/mafiatogether/service/VoteService.java
  src/test/java/mafia/mafiatogether/controller/VoteControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomTest.java
  src/test/java/mafia/mafiatogether/domain/status/StatusTest.java
Labels: Backend

#57 feat: 경찰 스킬 수정 및 예외처리
  src/main/java/mafia/mafiatogether/config/exception/CitizenException.java
  src/main/java/mafia/mafiatogether/config/exception/ExceptionCode.java
  src/main/java/mafia/mafiatogether/config/exception/PlayerException.java
  src/main/java/mafia/mafiatogether/domain/Player.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/job/Citizen.java
  src/main/java/mafia/mafiatogether/domain/job/Police.java
  src/test/java/mafia/mafiatogether/domain/job/PoliceTest.java
Labels: Backend

#59 feat: 밤 결과 조회 API 구현
  src/main/java/mafia/mafiatogether/config/exception/ExceptionCode.java
  src/main/java/mafia/mafiatogether/controller/RoomController.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/job/JobTarget.java
  src/main/java/mafia/mafiatogether/service/RoomService.java
  src/main/java/mafia/mafiatogether/service/dto/RoomNightResultResponse.java
  src/test/java/mafia/mafiatogether/domain/job/JobTargetTest.java
Labels: Backend

#61 feat: 채팅 직업 필드 추가
  src/main/java/mafia/mafiatogether/domain/Message.java
  src/main/java/mafia/mafiatogether/service/ChatService.java
  src/main/java/mafia/mafiatogether/service/dto/ChatResponse.java
  src/test/java/mafia/mafiatogether/controller/ChatControllerTest.java
Labels: Backend

#62 fix: 방 코드 검증 api 수정
  src/main/java/mafia/mafiatogether/domain/RoomManager.java
  src/test/java/mafia/mafiatogether/controller/RoomControllerTest.java
  src/test/java/mafia/mafiatogether/domain/RoomManagerTest.java
Labels: Backend

#63 fix: 잘못된 방 검증 로직 제거
  src/main/java/mafia/mafiatogether/service/RoomService.java
Labels: Backend

#65 QA 버그 픽스
  src/main/java/mafia/mafiatogether/config/exception/ExceptionCode.java
  src/main/java/mafia/mafiatogether/domain/Chat.java
  src/main/java/mafia/mafiatogether/domain/Player.java
  src/main/java/mafia/mafiatogether/domain/Room.java
  src/main/java/mafia/mafiatogether/domain/Vote.java
  src/main/java/mafia/mafiatogether/domain/job/JobTarget.java
  src/test/java/mafia/mafiatogether/controller/PlayerControllerTest.java
  src/test/java/mafia/mafiatogether/domain/status/StatusTest.java
Labels: bug, Backend

#66 fix: NONE 싱글톤 에러 픽스
  src/main/java/mafia/mafiatogether/domain/Room.java
Labels: bug, Backend, Hotfix
